% Generate Main Div HTML based on rcsv data, and insert it in template
% 

function ghh_homeHTMLCell=ghh_GenerateHomeHTML( ...
    CatList, ...
    CatLink, ...
    CatMenuNo, ...
    ImageSource, ...
    Title, ...
    Status, ...
    HTMLTitle)



    % Generate HTML
    ghh_CatHTML='<div id="homeMainDiv">';
    for categ=1:numel(CatList)
        ghh_CatHTML=[ghh_CatHTML, ...
            '	<div class="homeCatDiv" id="',CatLink{categ},'">',upper(CatList{categ}),'</div>\r', ...
            '	<div class="homeFigDiv">\r'];
        for menu=1:numel(CatMenuNo{categ}) %For each categorie, create recipe image from list

            menuID=CatMenuNo{categ}(menu);
            
            % Add status and recipe selector
            if ~(strcmpi(Status{menuID},'incomplet') || strcmpi(Status{menuID},'incomplete'))
                ghh_AddStatus='';
                
                if ~isempty(Status{menuID}) && numel(Status{menuID})<25 %avoid if too long!
                    ghh_AddStatus=['			<p class="homeImgNote">',Status{menuID},'</p>\r'];
                end
                
                ghh_CatHTML=[ghh_CatHTML, ...
                    '		<a class="homeImgList" href="',HTMLTitle{menuID},'.html" id="homeRecipe',num2str(menuID), ...
                        '" style="background-image: url(./images/recipe/thumb286/',ImageSource{menuID}, ...
                        '); background-size: cover; background-position: 50% 50%; background-repeat: no-repeat;">\r', ...
                    '			<p class="homeImgTitle">',Title{menuID},'</p>\r', ...
                    ghh_AddStatus, ...
                    '		</a>\r'];
            end
        end
        ghh_CatHTML=[ghh_CatHTML, ...
            '	</div>\r', ...
            ];
    end
        ghh_CatHTML=[ghh_CatHTML, ...
            '</div>\r';
            ];

    ghh_homeHTMLCell=regexp(ghh_CatHTML,'\\r','split')';
    


end