% Generate Main Div HTML based on rcsv data, and insert it in template
% 

function gph_photoHTMLCell=gph_GeneratePhotoHTML( ...
    ImageSource, ...
    MainTitle,...
    HTMLTitle,...
    AddImages, ...
    Status)



    % Generate HTML
    gph_photoHTML=['<div id="homeMainDiv">\r', ...
        '	<div class="galleryFigDiv gMagPopup">\r'];
    
    for iI=1:numel(ImageSource)
        if ~(strcmpi(Status{iI},'incomplet') || strcmpi(Status{iI},'incomplete') || strcmpi(ImageSource{iI},'foodinprogress.png'))
            gph_photoHTML=[gph_photoHTML, ...
                '		<a href="./images/recipe/',ImageSource{iI},'" title="',MainTitle{iI},'" linkref="',HTMLTitle{iI},'.html">\r', ...
                '			<div class="imgGallery" style="background: url(./images/recipe/thumb286/',ImageSource{iI},') 50% 50% / cover no-repeat;">\r', ...
                '			</div>\r', ...
                '		</a>\r'];

            for iAI=1:numel(AddImages{iI}) %For each categorie, create recipe image from list
                gph_photoHTML=[gph_photoHTML, ...
                    '		<a href="./images/recipe/',AddImages{iI}{iAI},'" title="',MainTitle{iI},'" linkref="',HTMLTitle{iI},'.html">\r', ...
                    '			<div class="imgGallery" style="background: url(./images/recipe/thumb286/',AddImages{iI}{iAI},') 50% 50% / cover no-repeat;">\r', ...
                    '			</div>\r', ...
                    '		</a>\r'];
            end
        end
    end
    
    gph_photoHTML=[gph_photoHTML, ...
        '</div>\r';
        ];

    gph_photoHTMLCell=regexp(gph_photoHTML,'\\r','split')';
    


end