% Generate MainDiv HTML for each Recipe, and insert it in template

function grh_recipeHTMLCell=grh_GenerateRecipeHTML( ...
    MainTitle, ...
    ImageSource, ...
    AddImages, ...
    BGPos, ...
    Note, ...
    InfoGroup, ...
    Inspiration, ...
    SourceLink, ...
    Sec1_Title, ...
    Sec1_Ingr, ...
    Sec1_Prep, ...
    Sec2_Title, ...
    Sec2_Ingr, ...
    Sec2_Prep, ...
    Sec3_Title, ...
    Sec3_Ingr, ...
    Sec3_Prep)

    %Pre-treatment of variables
    
    %Get background cover code
    imbc_BackgroundCodeCover=imbc_ImageCoverCode(BGPos);
    
    % Recipe Note Info and Source
    irns_recipeInfoCode=irns_recipeInfoSource( ...
        InfoGroup, ...
        Inspiration, ...
        SourceLink);
    
    % Prepare Ingr and Prep sections
    iprp_1Code=iprp_IngPrepCode(Sec1_Title, ...
        Sec1_Ingr, ...
        Sec1_Prep, ...
        1);
    iprp_2Code=iprp_IngPrepCode(Sec2_Title, ...
        Sec2_Ingr, ...
        Sec2_Prep, ...
        2);
    iprp_3Code=iprp_IngPrepCode(Sec3_Title, ...
        Sec3_Ingr, ...
        Sec3_Prep, ...
        3);
    
    %Prepare Note at the bottom if existing
    if ~isempty(Note)
        AddMainNote=[ ...
    		'	<div class="subNoteDiv">\r', ...
			'		<image class="subNoteImg" src="./images/Note.jpg" alt="Note:">\r', ...
			'		<p class="subNote">',Note,'</p>\r', ...
			'	</div>\r'];
    else
        AddMainNote='';
    end
    
    % Prepare additional picture for gallery preview
    grh_AddImageCode=''; %<a href="./images/recipe/bavetteboeuf.jpg"></a>\r'
    for iA=1:numel(AddImages)
        grh_AddImageCode=[grh_AddImageCode ...
            '			<a href="./images/recipe/',AddImages{iA},'" title="',MainTitle,'" linkref=""></a>\r'; ...
        ];
    end
    
    
    
    % Generate HTML
    grh_recipeHTML=[ ...
        '<div id="fullRecipeDiv">\r', ...
        '	<div id="mainTitleDiv" style="background: url(./images/recipe/', ... % TITLE SECTION START
            ImageSource,') ',imbc_BackgroundCodeCover,';">\r', ...
        '		<div class="darkerBackground">\r', ...
        '		</div>\r', ...
        '		<div  class="gMagPopup" id="mainTitleImg" style="background: url(./images/recipe/',ImageSource,') 50% 50% / cover no-repeat;">\r', ...
        '			<a class="aSelector" href="./images/recipe/',ImageSource,'" title="',MainTitle,'" linkref=""></a>\r', ...
		grh_AddImageCode, ...
        '		</div>\r', ...
        '		<div id="mainTitleText"><p class="RecipeTitle">',upper(MainTitle),'</p>\r', ...
        irns_recipeInfoCode, ...
        '		</div>\r', ...
        '	</div>\r', ...     % TITLE SECTION END
        iprp_1Code, ...
        iprp_2Code, ...
        iprp_3Code, ...
        AddMainNote, ...
        '</div>\r', ... 
        ];
    


    grh_recipeHTMLCell=regexp(grh_recipeHTML,'\\r','split')';
    
end

function imbc_BackgroundCodeCover=imbc_ImageCoverCode(BGPos)

    %Check if bottom or top
    if isempty(BGPos)
        imbc_BackgroundCodeCover='50% 50% / cover no-repeat';

    else
        switch lower(BGPos)
            case 'bottom'
                imbc_BackgroundCodeCover='50% 100% / cover no-repeat';
            case 'top'
                imbc_BackgroundCodeCover='50% 0% / cover no-repeat';
            otherwise
                imbc_BackgroundCodeCover='50% 50% / cover no-repeat';
        end
    end
    
end


function irns_recipeInfoCode=irns_recipeInfoSource(InfoCell,Source,SourceLink)

    % Recipe Note Info and Source
    irns_recipeInfoCode='';
    for i=1:numel(InfoCell)
        irns_recipeInfoCode=[irns_recipeInfoCode, ...
            '			<p class="RecipeInfo">',InfoCell{i},'</p>\r'];
    end
    if isempty(SourceLink) %check if a link is needed
        irns_recipeInfoCode=[irns_recipeInfoCode, ...
            '		<p class="RecipeSource">',Source,'</p>\r'];
    elseif ~isempty(strfind(Source,':')) % if start with Source: aaa.com, only add link to text after :
        irns_recipeInfoCode=[irns_recipeInfoCode, ...
            '		<p class="RecipeSource">',Source(1:strfind(Source,':')+1), ...
                '<a class="whiteLink" target="_blank" href="',SourceLink,'">',Source(2+strfind(Source,':'):end),'</a></p>\r'];
    else
        irns_recipeInfoCode=[irns_recipeInfoCode, ...
            '		<p class="RecipeSource"><a class="whiteLink" target="_blank" href="',SourceLink,'">',Source,'</a></p>\r'];
    end
end

function    iprp_SecCode=iprp_IngPrepCode(SubTitle,Ingr,Prep,SectionNo)
    
    % Pre-treatment
    
    % Skip if section 2 or 3 and no SubTitle
    iprp_SecCode='';
    if SectionNo==2 && isempty(SubTitle) || SectionNo==3 && isempty(SubTitle) 
        iprp_Skip=1;
    else
        iprp_Skip=0;
    end
    
    % Do not display subtitle of section 1 if empty
    if SectionNo==1 && isempty(SubTitle) 
        iprp_TitleCode='';
    else
        iprp_TitleCode=[ ...
        	'		<div class="RecipeSubTitle" id="RecipeSubTitle',num2str(SectionNo),'">',SubTitle,'</div>\r', ...
            ];
    end
    
    % Create Ingr List
    iprp_IngrCode='';
    for i=1:numel(Ingr)
        iprp_IngrCode=[iprp_IngrCode, ...
            '				<li>',Ingr{i},'</li>\r', ...
            ];
    end
    % Create Prep List
    iprp_PrepCode='';
    for i=1:numel(Prep)
        iprp_PrepCode=[iprp_PrepCode, ...
            '				<li>',Prep{i},'</li>\r', ...
            ];
    end
    
    if ~iprp_Skip
        % Assemble HTML Code
        iprp_SecCode=[ ...
            '	<div class="mainSubTitleDiv" id="mainSubTitle',num2str(SectionNo),'">\r', ...
            iprp_TitleCode, ...
            '		<div class="mainSubTitleIngr">\r', ...
            '			<p class="RecipeIngPrep">Ingrédients</p>\r', ...
            '			<ul id="SEC',num2str(SectionNo),'_INGR">\r', ...
            iprp_IngrCode, ...
            '			</ul>\r', ...
            '		</div>\r', ...
            '		<div class="mainSubTitlePrep">\r', ...
            '			<p class="RecipeIngPrep">Préparation</p>\r', ...
            '			<ol id="SEC',num2str(SectionNo),'_PREP">\r', ...
            iprp_PrepCode, ...
            '			</ol>\r', ...
            '		</div>\r', ...
            '	</div>\r', ...
            ];

    end

end